### ISSUE TITLE
Can not find ijl15.dll

### ISSUE THREAD

**Issue by jp05935611** [reanox/MapleStory-tool#2]
白狐大您好，感謝您提供拔除HS的檔案，有個問題想請教，最近在一台win10電腦上使用，他會跑出can not find ijl15.dll的錯誤提示，但使用ori的那個ijl15.dll可以開，但就是會卡在HS，這個問題可以從哪裡破解呢？謝謝

**Comment by reanox** [comment]
需要調整一下編譯環境，並重新編譯

**Comment by kevinlin0638** [comment]
您好 我這邊也有遇到同樣問題 但似乎不是所有Win10都會發生
還不太清楚要從哪下手

**Comment by jp05935611** [comment]
您好，目前已有一陣子沒有研究。
可嘗試重新對語法編譯。
祝    愉快 順心


*Wenhsien Biank Wang*
-------------------------------------------------------
*Email-1:* jp05935611@gmail.com
*Email-2:* s110212049@stu.ntue.edu.tw
*Teacher**. *
*Physics, **Chemistry, and Natural Science.*
-------------------------------------------------------


kevinlin0638 <notifications@github.com> 於 2018年10月1日 週一 下午3:40寫道：
