### ISSUE TITLE
請問120的破功

### ISSUE THREAD

**Issue by steven0788** [reanox/MapleStory-tool#8]
大大想請問120的破功部分已成功生成dll,但進入遊戲仍無法破功,想請問該如何修復呢

**Comment by reanox** [comment]
如果是物理攻擊是能正常破功的
其他的我沒測試

**Comment by steven0788** [comment]
您好,我是使用VS2017進行ijl15.sln進行x86編譯,我電腦是W7 64位元 我編譯出來的檔案其他電腦卻不能正常執行,我能正常執行,破功部分也無法正常實行,可以請問該如何使用呢

**Comment by reanox** [comment]
dllmain.cpp內的破攻函數我預設是注解掉的

自己打開吧

**Comment by steven0788** [comment]
有打開欸😅
